name: test
manual_seed: 0

dataset:
  SubIndy:
    name: SubIndy
    type: NWBDataset
    path: /Users/yjy/Desktop/nd/NDToolbox/datasets/sub_indy/sub-Indy_desc-train_behavior+ecephys.nwb
    units:
      field: units        # the units field name in nwb file.
      bin_size: 0.001     # bin size, unit is seconds.
    trials:
      field: trials       # the trials field name in nwb file.
      start: start_time   # the column name of trial start time.
      stop: stop_time     # the column name of trial stop time.
    behavior: ['behavior/cursor_pos', 'behavior/finger_pos', 'behavior/finger_vel', 'behavior/target_pos']
    skip_fields: None

  SubMonk:
    name: SubMonk
    type: NWBDataset
    path: /Users/yjy/Desktop/nd/NDToolbox/datasets/sub-monk-g.nwb
    units:
      field: behavior/spike_counts
    trials:
      field: trials
    behavior: ['behavior/cursor']


experiment:
  exp_1:
    model:
      type: WienerCascadeRegression
      degree: 3
    train:
      dataset: SubIndy
      split:
        type: ---------
      smooth: 0.05      # the standard deviation of the Gaussian to use for smoothing, in seconds
      lag: 0.12         # Lag velocity by 0.12 seconds relative to neural data.
      target: ['behavior/finger_vel']
    val_1:
      dataset: SubIndy
      split:
        type: ---------
      smooth: 0.05
      lag: 0.12
      target: ['behavior/finger_vel']
    val_2:
      ---------
    metrics:
      R2:
        type: calculate_R2
      CC:
        type: calculate_cc

  exp_2:
    model:
      type: SupportVectorRegression
      path: ---------
      is_copy: False
    test:
      dataset: SubMonk
      smooth: 0.5
      lag: 0.15
      target: ['behavior/cursor']
    metrics:
      MAE:
        type: calculate_mae
      MSE:
        type: calculate_mse
